### ISSUE TITLE
Add a delete icon next to the task 

### ISSUE THREAD

**Issue by Akanksha1212** [bartekpacia/mentorship-client#100]
**Is your feature request related to a problem? Please describe.**
Delete option appears when the user clicks on the task. There is no clear indicator like an icon for the same. 

**Describe the solution you'd like**
A delete icon next to the task should be added. Delete task dialog box should appear when the icon is clicked instead of the task.

**Additional context**
Current Version
<img src="https://user-images.githubusercontent.com/20701948/84576200-81c20380-add0-11ea-9bcf-84a73376272a.gif " width="250" height="450" />

**Comment by bharat-1809** [comment]
Can I work on it?

**Comment by Akanksha1212** [comment]
Sure. Go ahead @bharat-1809

**Comment by techno-disaster** [comment]
I suggest making a ListTile and adding the icon using the ```trailing``` property. @bharat-1809 . Feel free to use if you find anything better than this

**Comment by bharat-1809** [comment]
@Techno-Disaster @Akanksha1212 @bartekpacia Instead of a delete button and showing the dialog box can we implement swipe to dismiss, If it fits the theme of the app? and also, a snackBar will be displayed containing the undo action.

**Comment by techno-disaster** [comment]
> @Techno-Disaster @Akanksha1212 @bartekpacia Instead of a delete button and showing the dialog box can we implement swipe to dismiss, If it fits the theme of the app? and also, a snackBar will be displayed containing the undo action.

imo a delete button would be better. what do you think @anitab-org/mentorship-flutter-maintainers

**Comment by bartekpacia** [comment]
I'd also lean towards delete button (trash can icon), it's more discoverable and obvious.

**Comment by Anirudhk07** [comment]
Can I take this ?

**Comment by Akanksha1212** [comment]
Hi @Anirudhk07 This has been assigned to @bharat-1809 and the PR is up already. You can find more issues to work by looking for Status: Available label.
