### ISSUE TITLE
When opening the Calendar on Send Request screen a debug toast is shown on android

### ISSUE THREAD

**Issue by isabelcosta** [bartekpacia/mentorship-client#120]
## Description
As a developer of mentorship system,
I need to not show debug code and prints,
so that I can provide a good non-weird experience to the end-user.

When opening the Calendar on Send Request screen a debug toast is shown on the android version of the app.

## Screenshots of the issue

This screenshot don't include the toast, because I didn't manage to take the screenshot before it disappeared, but these are the screens affected.

| Send Request Screen | Calendar widget screen |
|-|-|
| ![WhatsApp Image 2020-08-01 at 12 37 24](https://user-images.githubusercontent.com/11148726/89101145-39e55300-d3f5-11ea-9401-c590096b5c10.jpeg) | ![WhatsApp Image 2020-08-01 at 12 37 18](https://user-images.githubusercontent.com/11148726/89101148-3c47ad00-d3f5-11ea-8386-78c34d098bec.jpeg) |

### Update [Required]
- [ ] The toast should not appear when opening the calendar widget

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hours

**Comment by justdvnsh** [comment]
Hi @isabelcosta . I'd like to be assigned this issue and start contributing to the organization

**Comment by isabelcosta** [comment]
@justdvnsh I already assigned you the other issue you asked for, so I will leave this available :)

**Comment by justdvnsh** [comment]
@isabelcosta sure. thanks

**Comment by dwvicy** [comment]
Hello, @isabelcosta! I would like to work on this issue to begin with my contributions. Can you please assign it to me? 
(I've rectified it locally, I'll create a PR as soon as I'm assigned)

**Comment by isabelcosta** [comment]
@justdvnsh is assigned and working on it
@dwvicy I can redirect you other issues :) we have plenty here!

@justdvnsh are you facing any issues with this task? If so please let us know, and perhaps @dwvicy can help you :)

**Comment by isabelcosta** [comment]
@dwvicy yes you can sorry! I will assign to you
