### ISSUE TITLE
Find Members button sometimes does not work

### ISSUE THREAD

**Issue by isabelcosta** [bartekpacia/mentorship-client#123]
**Describe the bug**

Sometimes when clicking Find Members button on "Current Relation" screen, the button does not work.

I see 2 things happening here: The find members button does not work in the second time and the first time, when I click the button I see that the menu option did not change to "Members List" Screen.

**To Reproduce**
1. Login into the app with valid credentials (register a new account if you don't have one yet)
2. Go to 'Current relation' screen, the middle 3rd option in the bottom menu
3. Click on 'Find Members' button
**Observation:** the bottom menu option keeps showing "Current Relation" as the selected option
4. Click other option on the menu, could be 'Members' or 'Home' screen
5. Then go again to 'Current Relation' screen
6. Click 'Find Members' button
**Observation:** Members screen does not show up

**Expected behavior**

The "Find Members" button always works and the menu tab changes to "Members" screen indicating redirection to the screen.

**Screenshots**

<img src="https://user-images.githubusercontent.com/11148726/89101780-3228ad00-d3fb-11ea-9836-deec45d914e6.jpeg" alt="tabs showing when I am not in a relation" width="200"/>

**Smartphone (please complete the following information):**
 - Device: Huawei P8
 - OS: Android
 - Version 🤷‍♀️ 

**Additional context**

N/A

**Comment by techno-disaster** [comment]
Duplicate issue #113 which already has a PR up
