### ISSUE TITLE
Adding media queries and google fonts.

### ISSUE THREAD

**Issue by j-kon** [bartekpacia/mentorship-client#131]
**Is your feature request related to a problem? Please describe.**
Adding a profile picture in the profile sections [...]

**Describe the solution you'd like**
so am going to be adding media queries and making the anitab logo background to be transparent.

**Describe alternatives you've considered**

**Additional context**
Permit me to change the font to google fonts'

**Comment by isabelcosta** [comment]
@j-kon can you be more clear in the description. I don't understand the change you are trying to do. What are the media queries and google fonts for? Is this something that changes UI or improves code quality? If @anitab-org/mentorship-flutter-maintainers including me understand your issue then we can validate and assign this to you :)

**Comment by techno-disaster** [comment]
@j-kon What do you mean by adding profile picture? We do not have a feature for profile picture setup on backend yet. Also where would you be adding MediaQuerys? Also fyi we are not using any custom fonts in the app yet, we will change the font/UI ones the @anitab-org/design-team comes up with something

**Comment by j-kon** [comment]
So sorry for the late response, a lot has happened. @Techno-Disaster has said changing of the profile picture is not on backend yet.  @isabelcosta Adding google font is more clear and user friendly. I will check the android mentorship app and see what I can add to the flutter mentorship app.
