### ISSUE TITLE
Remove delete account button

### ISSUE THREAD

**Issue by techno-disaster** [bartekpacia/mentorship-client#134]
**Is your feature request related to a problem? Please describe.**
We don't want to allow the user to delete his/her account as it messes the db at the backend.

**Describe the solution you'd like**
Remove the delete account option from the UI from the settings page

**Comment by techno-disaster** [comment]
@anitab-org/coding-team does anyone want to pick this up? Should be easy.

**Comment by HaripriyaB** [comment]
Can I take it up?

**Comment by techno-disaster** [comment]
sure @HaripriyaB

**Comment by jatinjain001** [comment]
I want to take it up

**Comment by techno-disaster** [comment]
> I want to take it up

This issue was already taken up and the PR is up #135

**Comment by shantanu1k** [comment]
Actually the button is still visible.....Can I remove it completely?
