### ISSUE TITLE
Add badges for Stars and Forks in the Readme

### ISSUE THREAD

**Issue by yashasvimisra2798** [bartekpacia/mentorship-client#140]
**Description**
The Readme does not have the badges stating the current number of stars and forks on this repository

**Comment by yashasvimisra2798** [comment]
I would like to work on the issue please assign this to me. Thanks

**Comment by techno-disaster** [comment]
@anitab-org/mentorship-flutter-maintainers do we need these badges?

**Comment by jatinjain001** [comment]
I would like to work on this.
please assign it to me

**Comment by techno-disaster** [comment]
Closing as this is not needed as of now as we can already see these stats on top of the repo page.
