### ISSUE TITLE
Add docs for testing team

### ISSUE THREAD

**Issue by techno-disaster** [bartekpacia/mentorship-client#141]
Recently a PR was merged which was supposed to ease out testing apks, without Android Studio, but most people are unaware about this. We need to create a doc which tells more about this feature. More info [here](https://github.com/anitab-org/mentorship-flutter/pull/126)

**Comment by techno-disaster** [comment]
@anitab-org/coding-team would someone like to pick this up?

**Comment by SubhamChoudhury** [comment]
@Techno-Disaster can I work on this? as a first timer, please guide me through it.

**Comment by SubhamChoudhury** [comment]
@Akanksha1212  thank you ma'am. Ma'am can you please guide me through the issue, I am a beginner.

**Comment by SubhamChoudhury** [comment]
Thank you ma'am. Since I am a beginner, can you please mentor me through
the steps

Subham Choudhury

**Comment by rpattath** [comment]
This is where you get the [apk](https://github.com/anitab-org/mentorship-flutter/tree/apk) from to test the app. You have to download the .apk to your android device and run the app. Try to install the app using the apk if you have an android device, so that you can get the screenshots and can describe the process more clearly.
I think @Techno-Disaster has implemented apk for each PR but I am not sure where to get that apk from.

**Comment by techno-disaster** [comment]
> This is where you get the [apk](https://github.com/anitab-org/mentorship-flutter/tree/apk) from to test the app. You have to download the .apk to your android device and run the app. Try to install the app using the apk if you have an android device, so that you can get the screenshots and can describe the process more clearly.
> I think @Techno-Disaster has implemented apk for each PR but I am not sure where to get that apk from.

Below each PR if you go the the checks tab you will see a "artifacts" drop-down. If you click on that you will be able to download a zip file which has the apk

**Comment by techno-disaster** [comment]
@SubhamChoudhury any updates on this issue?

**Comment by SubhamChoudhury** [comment]
> @SubhamChoudhury any updates on this issue?

Sir, I feel I am not versed with the necessary pre-requisites for the issue. I am not unable to work on it.

**Comment by techno-disaster** [comment]
> > @SubhamChoudhury any updates on this issue?
> 
> Sir, I feel I am not versed with the necessary pre-requisites for the issue. I am not unable to work on it.

@SubhamChoudhury No worries, could you tell us where you are stuck so that we can help you out?

**Comment by SubhamChoudhury** [comment]
> > > @SubhamChoudhury any updates on this issue?
> > 
> > 
> > Sir, I feel I am not versed with the necessary pre-requisites for the issue. I am not unable to work on it.
> 
> @SubhamChoudhury No worries, could you tell us where you are stuck so that we can help you out?

Sir, am not skilled in flutter yet. So I don't know how the codebase works. Am sorry for that and I don't know how to proceed ahead

**Comment by techno-disaster** [comment]
> > > > @SubhamChoudhury any updates on this issue?
> > > 
> > > 
> > > Sir, I feel I am not versed with the necessary pre-requisites for the issue. I am not unable to work on it.
> > 
> > 
> > @SubhamChoudhury No worries, could you tell us where you are stuck so that we can help you out?
> 
> Sir, am not skilled in flutter yet. So I don't know how the codebase works. Am sorry for that and I don't know how to proceed ahead

@SubhamChoudhury  this is a documentation project tho. Incase you want to be unassigned from this, please let me know

**Comment by SubhamChoudhury** [comment]
Sir, can you send me a sample documentation so that I can take reference
and work on it.

Subham Choudhury

**Comment by techno-disaster** [comment]
@rpattath can you show me one of the docs you refer for testing? Although I'm not sure what he means by "sample documentation". Also were you able to locate the apk for each PR @rpattath ?

**Comment by rohankumawat** [comment]
I would like to work on this!
I think that I've to make documentation for the testers on how to test a new feature of the app.
Can you assign me this?

**Comment by techno-disaster** [comment]
> I would like to work on this!
> I think that I've to make documentation for the testers on how to test a new feature of the app.
> Can you assign me this?

Done.

**Comment by rohankumawat** [comment]
I've tried to make a Guide for the Testing team.
I hope it's fine. 
Thank you 😄.
