### ISSUE TITLE
Confirm password field while changing password

### ISSUE THREAD

**Issue by KevalPrajapati** [bartekpacia/mentorship-client#151]
**Is your feature request related to a problem? Please describe.**
The android app has a confirm password field while changing password which I think is needed in the flutter app.

<img src="https://user-images.githubusercontent.com/63007835/104597995-0b55ee80-569c-11eb-9440-581f0305ce7a.png" width="200" height="400" />

**Describe the solution you'd like**
If the issue is valid, I would like to work on it. This can be done in the same way as it is done in the android app.

**Comment by techno-disaster** [comment]
@anitab-org/coding-team first timer issue available.

**Comment by KevalPrajapati** [comment]
> @anitab-org/coding-team first timer issue available.

I am first timer. Please assign me the issue.

**Comment by keshakaneria** [comment]
> > @anitab-org/coding-team first timer issue available.
> 
> I am first timer. Please assign me the issue.

Go for it

**Comment by KevalPrajapati** [comment]
> > > @anitab-org/coding-team first timer issue available.
> > 
> > 
> > I am first timer. Please assign me the issue.
> 
> Go for it

Someone added the field

**Comment by keshakaneria** [comment]
Since this issue is already created, closing this issue.
