### ISSUE TITLE
Create CONRIBUTING.md file

### ISSUE THREAD

**Issue by bartekpacia** [bartekpacia/mentorship-client#2]
**Is your feature request related to a problem?**
`CONTRIBUTING.md` is the file where, by convention, new contributors can learn how to help develop the project. 
It should include information like:
– it is necessary to follow the Issue and Pull Request templates
– use only the latest `stable` version of Flutter

There's definitely more to add there but those are the few I can think of currently. 

**Describe the solution you'd like**
create `CONTRIBUTING.md` file

**Describe alternatives you've considered**
none

**Comment by gaurivn** [comment]
I would like to work on this issue.

**Comment by techno-disaster** [comment]
@gaurivn  sure, remember to add what bartek has mentioned in his issue and change channel to beta instead of stable

**Comment by gaurivn** [comment]
@Techno-Disaster , sure. I changed to beta channel, should I write the same instead of stable in CONTRIBUTING.md
