### ISSUE TITLE
Add a Contact section

### ISSUE THREAD

**Issue by isabelcosta** [bartekpacia/mentorship-client#20]
**Is your feature request related to a problem? Please describe.**

A new contributor that arrives to this repository may not be aware of where the community discusses projects other than GitHub, so its nice to have a Contact section just like there is for [anitab-org/mentorship-backend](https://github.com/anitab-org/mentorship-backend).

**Describe the solution you'd like**

Create a new section on README same as the one on [anitab-org/mentorship-backend](https://github.com/anitab-org/mentorship-backend) that share the same Zulip stream.

**Describe alternatives you've considered**

None

**Additional context**

Great issue for newcomers

**Comment by nandini45** [comment]
@Isabelcosta
Can I work on it??

**Comment by isabelcosta** [comment]
sure you can :) @nandini45
