### ISSUE TITLE
Documentation Issue Template

### ISSUE THREAD

**Issue by techno-disaster** [bartekpacia/mentorship-client#26]
**Is your feature request related to a problem? Please describe.**
Recently wanted to create a issue to add something in the documentation, but both the feature request and bug report templates don't really fit properly for this problem
Editing documentation can sometimes fall under bug issue, but documentation definitely doesn't fall under features.
**Describe the solution you'd like**
Add a issue template which will help contributors add issues related to editing the documentation specifically

**Comment by gaurivn** [comment]
@Techno-Disaster , can I work on this issue?

**Comment by techno-disaster** [comment]
@gaurivn this is a easy task
sorry forgot to add the first timers label

**Comment by gaurivn** [comment]
Okay

**Comment by techno-disaster** [comment]
Not really needed anymore
