### ISSUE TITLE
Improve about app feature

### ISSUE THREAD

**Issue by bartekpacia** [bartekpacia/mentorship-client#28]
**Is your feature request related to a problem? Please describe.**
Currently about app feature looks displays very limited set of information.

![demo](https://user-images.githubusercontent.com/40357511/80771884-13452100-8b55-11ea-9573-af1ec384811c.gif)

**Describe the solution you'd like**
I'd like to have a full `AboutAppPage` with a lot of information about AnitaB, the awesome contributors and how one can start contributing :)

**Describe alternatives you've considered**
*no alternatives*

**Comment by gaurivn** [comment]
I would like to work on this issue.

**Comment by techno-disaster** [comment]
Can i self assign this? would like to work on it. 
cc @isabelcosta

**Comment by isabelcosta** [comment]
go go @Techno-Disaster :)

**Comment by techno-disaster** [comment]
@bartekpacia are the current licenses just place holders? also @isabelcosta can i remove the licences? we don't need them atm not before release ofc and they aren't even the proper licensees required ig

**Comment by isabelcosta** [comment]
@Techno-Disaster  Will leave that decision up to y'all, I never heard of this feature. For me you can take it out, if this needs more thought

**Comment by techno-disaster** [comment]
> @Techno-Disaster Will leave that decision up to y'all, I never heard of this feature. For me you can take it out, if this needs more thought

cools, i just wanted to know if we need to have some licenses in the app officially, like from AnitaB or something.

**Comment by isabelcosta** [comment]
I don't know as of now, but its nice to bring that up on Zulip

**Comment by techno-disaster** [comment]
<details>
<summary>Current UI</summary>
<br>

![image](https://user-images.githubusercontent.com/52817235/81308223-28fb9e80-909f-11ea-97d2-61d6f5dcd750.png)

</details>

The about page is almost done. Please help me with the content we have to add in it by editing this [doc](https://docs.google.com/document/d/1YSwVkrj7YTkljVA1BjZ1CAcBU3QlOLxNl-A6SwDtpFU/edit?usp=drivesdk)

**Comment by bartekpacia** [comment]
Looks great @Techno-Disaster.
Regarding the licenses, they are real according to [the docs](https://api.flutter.dev/flutter/material/showAboutDialog.html). I'd leave them.

**Comment by techno-disaster** [comment]
thanks Bartek.
also what data do i add to the page? current data is just some placeholder. I have asked several times to edit the doc, but no one's added anything. Should i keep the data like this for now? as its not really important. We can change it while releasing if required.
cc : @isabelcosta

**Comment by bartekpacia** [comment]
@Techno-Disaster I meant that the "general scaffold" looks great. We can merge this as a base to serve for future improvements. Contributors will have an easier time adding new stuff there when the basics are already done :)

**Comment by techno-disaster** [comment]
> @Techno-Disaster I meant that the "general scaffold" looks great. We can merge this as a base to serve for future improvements. Contributors will have an easier time adding new stuff there when the basics are already done :)

cools. will send a PR asap
