### ISSUE TITLE
Create Reporting Guidelines file

### ISSUE THREAD

**Issue by isabelcosta** [bartekpacia/mentorship-client#3]
**Is your feature request related to a problem?**

The project is missing Reporting Guidelines that should be the same in every repository.
Report Guidelines: https://github.com/anitab-org/anitab-org.github.io/blob/develop/reporting_guidelines.md

**Describe the solution you'd like**

Create a REPORTING_GUIDELINES.md in the root? or `.github` folder 

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by techno-disaster** [comment]
https://github.com/anitab-org/mentorship-flutter/pull/5 done, @isabelcosta it looks like i don't have write access to this repo, so i will not be able to review PR's untill requested

**Comment by techno-disaster** [comment]
added in #6 this also fixed the pull request template issue

**Comment by isabelcosta** [comment]
@Techno-Disaster in the PRs while we are not using the PR template please put `Fixes #issue` so that GitHub recognizes that should close the issue
