### ISSUE TITLE
Internal server error while signing up

### ISSUE THREAD

**Issue by HaripriyaB** [bartekpacia/mentorship-client#32]
**Describe the bug**
As a user,
When I attempt to signup for the mentorship app as a mentee it throws an internal server error and doesn't proceed further.

**To Reproduce**
1. Go to SignUp
2. Click on SighUp after filling the form
3. See error snackbar toast saying Internal server error

**Expected behavior**
Remove the error and proceed with signup process to signin with the app.
**Screenshots**
![Screenshot_2020-05-01-18-16-03-16_92746fe779a9c2c81c5c767d4a402904](https://user-images.githubusercontent.com/34762451/80806341-0a496380-8bd8-11ea-8e77-82d22a7eba75.png)

**Smartphone (please complete the following information):**
Android 9.0 Oppo 2020

**Comment by isabelcosta** [comment]
Great @HaripriyaB thank you for creating this issue! 🎉 
Knowing the password used here, could be helpful or not. Can you put it as text in the issue description?

**Comment by techno-disaster** [comment]
@isabelcosta does this work on the mentorship-android side? just want to make sure if its backend issue or a flutter client side issue

**Comment by isabelcosta** [comment]
Yap :) @Techno-Disaster 

| register                                                                                                                            | logged in                                                                                                                           |
|-------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------|
| ![Screenshot_20200501-133731](https://user-images.githubusercontent.com/11148726/80805928-34d3f600-8bb1-11ea-8e0d-a178a73e03e1.jpg) | ![Screenshot_20200501-133807](https://user-images.githubusercontent.com/11148726/80805915-2dace800-8bb1-11ea-9371-35489c60cefa.jpg) |

**Comment by isabelcosta** [comment]
@Techno-Disaster so its worth to see the logs of Flutter client when doing the registration, correct?

**Comment by techno-disaster** [comment]
> @Techno-Disaster so its worth to see the logs of Flutter client when doing the registration, correct?

yes i will look into it asap.
