### ISSUE TITLE
Update links to CoC, Contributing and Reporting guidelines README links

### ISSUE THREAD

**Issue by isabelcosta** [bartekpacia/mentorship-client#37]
## Description
As a first timer contributor,
I need guidelines to be up to date,
so that I can know how I can contribute to the community following current guidelines.

In the README file, links to Code of Conduct (CoC), Reporting guidelines and Contributing guidelines links have to be updated.

### Update [Required]
- [ ] Update CoC link to point to CoC located on the flutter repository
- [ ] Update Reporting Guidelines link to point to guidelines located on the flutter repository
- [ ] Update Contributing guidelines link to guidelines in the repository

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hours

**Comment by bartekpacia** [comment]
Isn't it already done in #29?

**Comment by isabelcosta** [comment]
I left a comment in the PR https://github.com/anitab-org/mentorship-flutter/pull/29#discussion_r419114407 @bartekpacia 
I didn't want to bother you again with this little change, since its not wrong, just an improvement. I figured it was a good first timer issue

**Comment by Akanksha1212** [comment]
Hi @isabelcosta, I would like to work on this issue.

**Comment by isabelcosta** [comment]
Go ahead @Akanksha1212 :)

**Comment by Akanksha1212** [comment]
Hi @isabelcosta, Thanks for letting me work on this issue. While updating README I noticed that COC link needs to be updated in Contributing.md as well which can be another first-timers-issue.

**Comment by isabelcosta** [comment]
Nice catch  @Akanksha1212 :) can you create that issue?

**Comment by Akanksha1212** [comment]
Sure @isabelcosta
