### ISSUE TITLE
MembersPage: add search feature

### ISSUE THREAD

**Issue by bartekpacia** [bartekpacia/mentorship-client#38]
**Is your feature request related to a problem?**
Currently the searching functionality in the [MembersPage](https://github.com/anitab-org/mentorship-flutter/blob/develop/lib/screens/home/pages/members/members_page.dart) doesn't work.

**Describe the solution you'd like**
Adding the search feature like in [the Android app](https://github.com/anitab-org/mentorship-android).

A final solution should preferably use BLoC pattern (like the rest of the app). I'm not quite sure how it would look like, *so the person who will be doing it*: implement it so that it will just work and we will iterate on it & improve.

**Comment by techno-disaster** [comment]
Status: on hold until pagination

**Comment by techno-disaster** [comment]
@anitab-org/mentorship-flutter-maintainers Can i work on this? :wink:  :)

**Comment by bartekpacia** [comment]
good luck:D

**Comment by techno-disaster** [comment]
Ok lol, i have no idea how to implement this, do we plan to use the /users/{userId} endpoint? or just load all the users first and check for names in the list?

**Comment by isabelcosta** [comment]
@Techno-Disaster You can use `search` query parameter.

Server: https://mentorship-backend-temp.herokuapp.com/

![image](https://user-images.githubusercontent.com/11148726/83174288-1579ab80-a112-11ea-9d85-ff1d83705cc1.png)

**Comment by techno-disaster** [comment]
> @Techno-Disaster You can use `search` query parameter.
> 
> Server: https://mentorship-backend-temp.herokuapp.com/
> 
> ![image](https://user-images.githubusercontent.com/11148726/83174288-1579ab80-a112-11ea-9d85-ff1d83705cc1.png)

@isabelcosta I tried entering the name in the search query field, but kept getting a empty list.I also tried entering the userId in the search field. What am i supposed to put in it?

**Comment by bartekpacia** [comment]
Have you tried doing it using sth like Postman just to exclude that it's API pitfall?

**Comment by techno-disaster** [comment]
> Have you tried doing it using sth like Postman just to exclude that it's API pitfall?

i tried curl from my command line, I really don't think its a pitfall. The search parameter should have better documentation imo

**Comment by techno-disaster** [comment]
Were you able go get any output?

**Comment by bartekpacia** [comment]
I cannot set up backend locally, getting really crazy errors that some native libraries can't be compiled.
Maybe you should create an issue for this in the backend repo?

**Comment by techno-disaster** [comment]
> I cannot set up backend locally, getting really crazy errors that some native libraries can't be compiled.
> Maybe you should create an issue for this in the backend repo?

exactly same issue here, although i thought that was some issue with my laptop specifically.

**Comment by isabelcosta** [comment]
> I cannot set up backend locally, getting really crazy errors that some native libraries can't be compiled.

🤯 

> Maybe you should create an issue for this in the backend repo?

It's open source 🤹‍♀️  @Techno-Disaster what should be better in the documentation in your own opinion? Do create an issue if you really feel there is something missing.
@bartekpacia what are the crazy errors?

If we want to get this flutter app working with the backend we have to be comfortable working with the backend and communicating issues we have with it. Otherwise, you will be dependent on other people to deal with backend. I or anyone who already ran the backend can help you both. Have you asked on zulip? (I am falling behind on Zulip messages to be honest)

**Comment by techno-disaster** [comment]
> > I cannot set up backend locally, getting really crazy errors that some native libraries can't be compiled.
> 
> 
> 
> > Maybe you should create an issue for this in the backend repo?
> 
> It's open source  @Techno-Disaster what should be better in the documentation in your own opinion? Do create an issue if you really feel there is something missing.
> @bartekpacia what are the crazy errors?
> 
> If we want to get this flutter app working with the backend we have to be comfortable working with the backend and communicating issues we have with it. Otherwise, you will be dependent on other people to deal with backend. I or anyone who already ran the backend can help you both. Have you asked on zulip? (I am falling behind on Zulip messages to be honest)

@isabelcosta I would like to know what exactly do we enter in the search field. An example in the swagger UI would be helpful. Also I am trying to get the backend ready by changing some versions, will ask on zulip if i get stuck again

**Comment by isabelcosta** [comment]
@Techno-Disaster its just a string, for example if you want to find a user called "Isabel" the query could be `"search": "isa"`.

I answered on Zulip as well. Could you create an issue on backend to improve documentation about `search` query parameter?

**Comment by techno-disaster** [comment]
@isabelcosta tried it, still getting an empty list. can you upload a screenshot with what exactly we have to put in the search box?

![image](https://user-images.githubusercontent.com/52817235/83334876-1273ec00-a2c7-11ea-98de-a6695aa5a048.png)

**Comment by isabelcosta** [comment]
What is the "%22" in the `search` parameter @Techno-Disaster ?
Remove the `"` quotes, that should not be there. When removing the quotes that will work

**Comment by techno-disaster** [comment]
> What is the "%22" in the `search` parameter @Techno-Disaster ?
> Remove the `"` quotes, that should not be there. When removing the quotes that will work

strangely searching ``` isa``` gives me a output but``` tech``` does not. does the search need a page too? like does the search only search on the particular page or whole database? Can you try searching ```tech```

**Comment by techno-disaster** [comment]
This is what I mean @isabelcosta ,searching ```isa``` gives me a result but ```urs``` or ```tech``` only gives me an empty list 

```urs```
![image](https://user-images.githubusercontent.com/52817235/83561796-1194c180-a536-11ea-9476-62f726d418c2.png)


```isa```
![image](https://user-images.githubusercontent.com/52817235/83561926-4d2f8b80-a536-11ea-8724-8c64f7f818e0.png)

**Comment by techno-disaster** [comment]
Status on hold until fixed on the backend. 
Issue : [#644](https://github.com/anitab-org/mentorship-backend/issues/644)
