### ISSUE TITLE
Grey screen when click cancel on Send Request calendar widget

### ISSUE THREAD

**Issue by isabelcosta** [bartekpacia/mentorship-client#39]
**Describe the bug**

When I click the "Cancel" button on the Calendar widget of Send Request screen, the screen appears as grey, instead of normal "Send Request" screen.

**To Reproduce**

1. Log in with any user (e.g.: ursula / 12345678)
2. Go to Members screen
3. Select a member, and click to see their profile
4. Click the button "Send Request"
5. Click the calendar icon to select an "end date"
6. Click "Cancel"
4. See grey screen

**Expected behavior**

The expected behavior would be: see the Send Request screen again (just like I would select a date), with end date unchanged.

**Screenshots**

| Calendar widget open | "Send Request" screen grey |
|-------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------|
| ![Calendar widget screen](https://user-images.githubusercontent.com/11148726/80920380-6e4e6200-8d67-11ea-9947-107a8bbf0576.jpeg) | ![Send request screen grey](https://user-images.githubusercontent.com/11148726/80920382-70b0bc00-8d67-11ea-891c-ca5ecdc57394.jpeg) |

**Smartphone (please complete the following information):**
 - Device: Huawei P10 Lite
 - OS: Android
 - Version 8

**Additional context**
N/A

**Comment by HaripriyaB** [comment]
Can I work on this? @isabelcosta

**Comment by isabelcosta** [comment]
@HaripriyaB yes :) will assign to you!

**Comment by HaripriyaB** [comment]
@isabelcosta I get to see this when I reproduce this issue. 
Is it a problem from backend??

![Screenshot_1589136682](https://user-images.githubusercontent.com/34762451/81507823-813fd400-931d-11ea-9a80-a66b26ea1d33.png)

**Comment by isabelcosta** [comment]
@HaripriyaB it is :) I hope to solve this with using pagination in the backend https://github.com/anitab-org/mentorship-backend/pull/541

**Comment by HaripriyaB** [comment]
> 
> 
> @HaripriyaB it is :) I hope to solve this with using pagination in the backend [anitab-org/mentorship-backend#541](https://github.com/anitab-org/mentorship-backend/pull/541)

okay so I'll wait till the backend is fixed :-) Do ping me if this backend issue is fixed.

**Comment by techno-disaster** [comment]
@HaripriyaB please start working on this, if you get stuck somewhere feel free to ask here, or on zulip

**Comment by HaripriyaB** [comment]
> 
> 
> @HaripriyaB please start working on this, if you get stuck somewhere feel free to ask here, or on zulip

Actually I found a bug when I reproduce this. So I think the title need to change? 

![Screenshot_2020-05-30-16-52-18-54_92746fe779a9c2c81c5c767d4a402904](https://user-images.githubusercontent.com/34762451/83326983-1afffe80-a296-11ea-8afc-ed1265f46c77.png)

**Comment by techno-disaster** [comment]
> > @HaripriyaB please start working on this, if you get stuck somewhere feel free to ask here, or on zulip
> 
> Actually I found a bug when I reproduce this. So I think the title need to change?
> 
> ![Screenshot_2020-05-30-16-52-18-54_92746fe779a9c2c81c5c767d4a402904](https://user-images.githubusercontent.com/34762451/83326983-1afffe80-a296-11ea-8afc-ed1265f46c77.png)

The title us running a release build, so we can't see the error there. Also if you already know what the error is no need to specify it, just write what was wrong in the PR.

**Comment by techno-disaster** [comment]
Hey @HaripriyaB  any updates? feel free to ask any doubts here if you are stuck
