### ISSUE TITLE
Create Code of Conduct

### ISSUE THREAD

**Issue by isabelcosta** [bartekpacia/mentorship-client#4]
**Is your feature request related to a problem?**

As a project within AnitaB.org Open Source Community, we need a code of conduct in the repository.

**Describe the solution you'd like**

The code of conduct should be the same as in every repo. Here is is the update one: https://github.com/anitab-org/anitab-org.github.io/blob/develop/code_of_conduct.md

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by techno-disaster** [comment]
@isabelcosta this should be in the root folder right? or the .github folder?

**Comment by isabelcosta** [comment]
I am not sure, it can be in either. What do you think? @Techno-Disaster

**Comment by techno-disaster** [comment]
Lets follow the code style from the previous repos and keep it in the root folder itself. @isabelcosta

**Comment by gaurivn** [comment]
I would like to work on this issue.

**Comment by isabelcosta** [comment]
@gaurivn go ahead :) I will assign this to you.
