### ISSUE TITLE
Add User Story template to project

### ISSUE THREAD

**Issue by isabelcosta** [bartekpacia/mentorship-client#40]
**Is your feature request related to a problem? Please describe.**
User story template is missing and this can be great for well-defined issues and guiding contributors.

Link to raw template on backend repo: https://raw.githubusercontent.com/anitab-org/mentorship-backend/develop/.github/ISSUE_TEMPLATE/user-story.md

**Describe the solution you'd like**

Add User Story template to `.github/ISSUE_TEMPLATE` folder

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Sanika1999** [comment]
Hi can I work on this @isabelcosta

**Comment by bartekpacia** [comment]
Sure @Sanika1999 , good luck :) 

@isabelcosta Is it okay when I assign people to work on issues? Or do we need your approval? I just want to help and take some work of triaging issues off you :)

**Comment by isabelcosta** [comment]
> Is it okay when I assign people to work on issues? Or do we need your approval? I just want to help and take some work of triaging issues off you :)

@bartekpacia yes of course, especially when you are a maintainer of the repository :P You are one of the code owners / maintainers of this project, so you are more than welcome and also this is part of your work as maintainer of this flutter project :)

**Comment by isabelcosta** [comment]
@bartekpacia My only thing, is when an issue is labeled as "First Timers Only", this means that the contributor assigned, is new to the repository. This is important for newcomers to feel motivated and get an opportunity to get acquainted with the repositories. If you only have issues for usual contributors, the project may not be as welcoming for first timers. @Sanika1999 is definitely new to the repo, so its fine :)

**Comment by techno-disaster** [comment]
@Sanika1999 please use the Fixes #ISSUE_NO. as mentioned in the PR template. this closes the linked issue when PR is merged

**Comment by Sanika1999** [comment]
> @Sanika1999 please use the Fixes #ISSUE_NO. as mentioned in the PR template. this closes the linked issue when PR is merged

OK got it!
