### ISSUE TITLE
Improve Current Relation screen when user in not in a relation

### ISSUE THREAD

**Issue by isabelcosta** [bartekpacia/mentorship-client#41]
## Description
As a user of the app,
I need a coherent current relation screen UI,
so that I can have a nice user experience.

The Current Relation screen has the same UI components, when user is or is not in a mentorship relation. The tabs should not appear when the user in not in a relation.

This is only a functional issue, no need to replicate the style of the Android app.

## Mocks

| Android project UI example | Current Flutter project UI |
|-------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------|
| ![WhatsApp Image 2020-05-03 at 18 01 35 (1)](https://user-images.githubusercontent.com/11148726/80920673-2fb9a700-8d69-11ea-80e5-c2d1c2c2173f.jpeg) | ![WhatsApp Image 2020-05-03 at 18 01 35](https://user-images.githubusercontent.com/11148726/80920674-32b49780-8d69-11ea-900c-1c60e581b692.jpeg) |

### Update [Required]
- [ ] Add a button to redirect the user to Members screen to select a new mentor/mentee, when user is not in a mentorship relation
- [ ] Hide tabs when user is not in a mentorship relation

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
3 hours

**Comment by nandini45** [comment]
@isabelcosta can i work on this issue?

**Comment by nandini45** [comment]
@isabelcosta  I am working on this ˘issue. will update in few days.

**Comment by techno-disaster** [comment]
@nandini45 can you update us on the progress of this issue?

**Comment by nandini45** [comment]
yeah sure @Techno-Disaster  i was having some issue in testing the app locally 
but after watching yesterday's session i am running it again. 
because of my other commitments i couldn't text you back.
i will solve the issue and submit the PR asap

**Comment by techno-disaster** [comment]
@nandini45  cools

**Comment by nandini45** [comment]
@Techno-Disaster  i had a question i only have to remove the details and task section and then add a button for finding members . right?

**Comment by nandini45** [comment]
@Techno-Disaster  i have to only remove the tab right? 
do i have to add button for finding members also?

**Comment by techno-disaster** [comment]
@nandini45 please check the acceptance criteria in the issue. 
you have to add the find members button if the user does not have a relationship else show the tabs

**Comment by bartekpacia** [comment]
@nandini45 If you have any problems, feel free to ask, we'll try to help and explain stuff.

**Comment by techno-disaster** [comment]
Hey, @nandini45 any updates on where you are with this issue?

**Comment by techno-disaster** [comment]
@nandini45 as we have received no updates from you regarding this issue I am unassiging you now. Thank You

**Comment by nandini45** [comment]
I was learning dart.. I am sorry. I will work on any other issue.

**Comment by techno-disaster** [comment]
> I was learning dart.. I am sorry. I will work on any other issue.

@nandini45  if you are just starting with flutter i would recommend you start with a first timer issue

**Comment by nandini45** [comment]
I solved a first timer issue. when the team started with this repository. 
i was having some issues in solving it but because of my other works. i couldn't focus on it and update within a 3 days time lapse. if you permit i will solve it again today and ask for any issue i faced

**Comment by techno-disaster** [comment]
@anitab-org/mentorship-flutter-maintainers can I work on this?

**Comment by techno-disaster** [comment]
@anitab-org/mentorship-managers can i work on this? PR for my other issues are already up

**Comment by satya7289** [comment]
Yup, Assigning you.
