### ISSUE TITLE
Update link to Code of Conduct 

### ISSUE THREAD

**Issue by Akanksha1212** [bartekpacia/mentorship-client#44]
## Description  
In CONTRIBUTING.md link to Code of Conduct(CoC) needs to be updated

### Update[Required]
- [ ] Update CoC link to point to CoC located in the flutter repository  
## Definition of done  
- [ ] All of the required items are completed.  
- [ ] Approval by 1 mentor.  
## Estimation
1 hour

**Comment by HaripriyaB** [comment]
I wish to work on it.
