### ISSUE TITLE
Add Travis Build Badge

### ISSUE THREAD

**Issue by techno-disaster** [bartekpacia/mentorship-client#47]
**Is your feature request related to a problem? Please describe.**
Follow the other AnitaB repos style and add a travis build status badge in readme
**Describe the solution you'd like**
Add the badge, you can refer to [this article](https://docs.travis-ci.com/user/status-images/) to do this.

PS : someone should start working on the documentation issue template issue #26 .This template does not feel right for this issue

**Comment by gaurivn** [comment]
@Techno-Disaster , can I work on this issue?

**Comment by bartekpacia** [comment]
@gaurivn Sure, good luck :)

**Comment by techno-disaster** [comment]
@gaurivn you already have one issue assigned. #27 . what's the progress on that?
cc: @bartekpacia

**Comment by bartekpacia** [comment]
I assume that he has enough time if he wants to work on these 2 issues.

**Comment by techno-disaster** [comment]
I'm not sure if we should assign 2 issues to the same person at the same time. Someone else may loose the chance to contribute if we do so. Also i should have raised this issue before unassiging and relabelling sorry for that.
@isabelcosta what do you think about this ?

**Comment by isabelcosta** [comment]
We have a rule I think of not letting people be assigned to multiple issues at the same time. The only exception I make is if the person already submitted the PR for one issue and is just waiting for reviewers... because I can take some time. So if @gaurivn is actively working on an issue, I would leave this to someone else. @Techno-Disaster @bartekpacia

**Comment by techno-disaster** [comment]
> We have a rule I think of not letting people be assigned to multiple issues at the same time. The only exception I make is if the person already submitted the PR for one issue and is just waiting for reviewers... because I can take some time. So if @gaurivn is actively working on an issue, I would leave this to someone else. @Techno-Disaster @bartekpacia

Thank You for the clarification :)

**Comment by gaurivn** [comment]
@Techno-Disaster , @isabelcosta , @bartekpacia , my progress on the other issue is that I tried changing the definitions of _availabletomentor and _needsmentoring many times over the past few days and even now but it's not working, the checkboxes remain checked as is shown on the issue. In that case I would like to be unassigned from the other issue and be assigned to this one.

**Comment by bartekpacia** [comment]
@gaurivn Sure, that's okay :) so good luck with the current issue

**Comment by gaurivn** [comment]
Thank you @bartekpacia  and btw I am a "she", not "he" :sweat_smile:

**Comment by isabelcosta** [comment]
@gaurivn thank you for correcting. This is helpful to avoid such mistakes :)

**Comment by bartekpacia** [comment]
@gaurivn Oops, sorry for that! I used he because in my language it sounded like a "male name". Thanks for correcting, in the future I'll use gender neutral pronouns :)
