### ISSUE TITLE
Add Splash Screen

### ISSUE THREAD

**Issue by techno-disaster** [bartekpacia/mentorship-client#50]
**Is your feature request related to a problem? Please describe.**
We see a black screen for the first 2-3 sec when we open the app. The Android version has a splash screen (mentorship logo) which prevents this. 

**Describe the solution you'd like**
Add a Splash screen and a  circular loading indicator below it, to let the app start.

**Comment by techno-disaster** [comment]
@isabelcosta  i have finished my work on this, can i assign myself and send a PR?

**Comment by bartekpacia** [comment]
@Techno-Disaster I think that by the rules, you should be assigned before working on this. but I might be wrong.

**Comment by techno-disaster** [comment]
> @Techno-Disaster I think that by the rules, you should be assigned before working on this. but I might be wrong.

correction: i have finished most of my work on it. 
But yes @bartekpacia , you are right i shouldn't have worked on it before getting assigned. Just didn't want to add another issue to the pile, because very few people are working on them.

**Comment by bartekpacia** [comment]
I think that's okay, but we should try to avoid similar situations in the future.

**Comment by isabelcosta** [comment]
Its fine @bartekpacia @Techno-Disaster :) thank you @bartekpacia for advocating for us following the community guidelines
