### ISSUE TITLE
Profile Page Editing Bug

### ISSUE THREAD

**Issue by techno-disaster** [bartekpacia/mentorship-client#51]
**Describe the bug**
The page does not slide up, so if we select any options below location it gets hidden behind the keyboard (keep in mind this position is relative depending on your keyboard height and dpi)

**To Reproduce**
1. Go to Profile Page
2. Click on edit and try editing the last option

**Expected behavior**
The page should slide up or some solution which you think would be more optimal than this. Please mention your approach to this in the comments below

**Screenshots**
![Screenshot_20200508-085808357](https://user-images.githubusercontent.com/52817235/81367179-1ec2ba00-910a-11ea-8b4a-fdd5a1c3889e.jpg)

Trying to edit "Skills" option in profile

**Comment by techno-disaster** [comment]
@anitab-org/mentorship-flutter-maintainers-1 can i work on this?

**Comment by bartekpacia** [comment]
Nobody else wants to do this, so I think it's okay. Good luck :) 

BTW Are maintainers allowed to self-assign PRs? @isabelcosta

**Comment by techno-disaster** [comment]
> Nobody else wants to do this, so I think it's okay. Good luck :)
> 
> BTW Are maintainers allowed to self-assign PRs? @isabelcosta

Nope, but i think we can ask other maintainers to assign it.

**Comment by bartekpacia** [comment]
hmm, okay👀

**Comment by techno-disaster** [comment]
3 day update: Still working on the issue, was stuck with some other stuff will try to complete this by tommorow

**Comment by isabelcosta** [comment]
> Nope, but I think we can ask other maintainers to assign it.

@bartekpacia @Techno-Disaster this would be a good approach. I just want to make sure we are doing this a community project and give the opportunity to others to work on it, and contribute with flutter if they wish to. You can claim it after creating the issue, but making sure someone knows about it. And also claim one at a time, instead claiming multiple issues at once.

There were occasions where I assign myself to backend issues because I had important knowledge about the history of the problem I was trying to solve. Like the PR to fix allow for the remote database connection to mitigate the non-persistent database issue.

**Comment by techno-disaster** [comment]
> > Nope, but I think we can ask other maintainers to assign it.
> 
> @bartekpacia @Techno-Disaster this would be a good approach. I just want to make sure we are doing this a community project and give the opportunity to others to work on it, and contribute with flutter if they wish to. You can claim it after creating the issue, but making sure someone knows about it. And also claim one at a time, instead claiming multiple issues at once.
> 
> There were occasions where I assign myself to backend issues because I had important knowledge about the history of the problem I was trying to solve. Like the PR to fix allow for the remote database connection to mitigate the non-persistent database issue.

@isabelcosta yes we are following the "you cannot assign yourself to your issue" policy as discussed in the zoom sessions. Also we are only allowing a person to claim 2 issues once the PR for the previous issue has been submitted according to the Contributing guidelines. I hope this is how it's meant to be. 
cc : @bartekpacia
