### ISSUE TITLE
Remove Travis "master" branch status

### ISSUE THREAD

**Issue by techno-disaster** [bartekpacia/mentorship-client#53]
**Describe the bug**
 PR #52 added travis build status badges, but it also included the badge for "master" branch which we will not be using atm and hence we have to remove it

**Expected behavior**
Have only "develop" branch build status in readme.

**Comment by isabelcosta** [comment]
important to mention this PR https://github.com/anitab-org/mentorship-flutter/pull/52 was the one that added it @Techno-Disaster

**Comment by techno-disaster** [comment]
> important to mention this PR #52 was the one that added it @Techno-Disaster

updated
