### ISSUE TITLE
Password Visibility Problem

### ISSUE THREAD

**Issue by robotjellyzone** [bartekpacia/mentorship-client#56]
**Describe the bug**
The Password field and Confirm passwords field are becoming visible at the same time even when we are just removing the visibility of only one at a time which is not a normal functioning in the app.

**To Reproduce**
1. Go to 'Sign Up'
2. Fill the password
3. Fill the confim password
4. Click the eye against both fields
5. You will see on clicking the eye against one will also make the other field visible

**Expected behavior**
On clicking the eye against the field, should only make that password field visible, not the other one.

**Screenshots**
![ms-flutter-bug](https://user-images.githubusercontent.com/36916536/81477508-bbce4180-9235-11ea-9bbf-07555cf15f1d.gif)

**Desktop :**
 - Platform : Android Studio

**Smartphone :**
 - Device: Android Emulator

**Additional context**
Make sure to allow only one field to be visible at a time

**Comment by HaripriyaB** [comment]
Can I work on this? It's my first time contributing for code. @robotjellyzone

**Comment by robotjellyzone** [comment]
Hi @HaripriyaB no you can't work on this as you have already worked on first timers issue which is this one #45 so, according to guidelines you can't even if it is coding one but still it is first timers only so, you can't work on this . i hope you can understand :)

**Comment by HaripriyaB** [comment]
> 
> 
> Hi @HaripriyaB no you can't work on this as you have already worked on first timers issue which is this one #45 so, according to guidelines you can't even if it is coding one but still it is first timers only so, you can't work on this . i hope you can understand :)

Okay chill. I accept. Thanks for the reply.

**Comment by techno-disaster** [comment]
@robotjellyzone i think that is the way it should work. If you are confirming password you would like to see whats the diff in the two passwords at the same time right?
cc: @bartekpacia

**Comment by robotjellyzone** [comment]
@Techno-Disaster as far as I have seen in other apps, this sort of thing was not there! I hope you must also have seen in other apps that if you click on the eye of one it should only make one to be visible at a time

**Comment by techno-disaster** [comment]
@robotjellyzone I just think its more convenient for the user while setting up an account to see both the password feilds during confirm password. 
@anitab-org/mentorship-flutter-maintainers-1 what do you suggest

**Comment by bartekpacia** [comment]
IMO the current behavior is OK.

**Comment by techno-disaster** [comment]
Yes, i think we can close this issue. Feel free to open it incase you feel otherwise

**Comment by robotjellyzone** [comment]
This sort of issue is not there even on mentorship-android @Techno-Disaster but that's ok if you think its not an issue .
