### ISSUE TITLE
Create documentation about iOS setup / run

### ISSUE THREAD

**Issue by isabelcosta** [bartekpacia/mentorship-client#58]
## Description

As an iOS developer,
I need to know how to setup / run the app in a iOS environment / device,
so that I can contribute to the iOS part of the application.

Maybe we could create a separate markdown document and mention that in the README.

### Update [Required]
- [ ] Create a markdown document explaining setup for iOS

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation

🤷‍♀️

**Comment by gaurivn** [comment]
I would like to work on this issue.

**Comment by techno-disaster** [comment]
@isabelcosta what difference between android and iOS app running should be mentioned?just the running of a virtual device on mac, using xcode? Because the flutter run command is same for both platforms, and installing flutter on a mac is already there on the readme.

**Comment by Techno-Disaster** [comment]
> @isabelcosta what difference between android and iOS app running should be mentioned? Because the flutter run command is same for both platforms, and installing flutter on a mac is already there on the readme

just the running of a virtual device on mac, using xcode?

**Comment by isabelcosta** [comment]
> just the running of a virtual device on mac, using xcode?

Yap @Techno-Disaster :) that is it.

**Comment by techno-disaster** [comment]
> > just the running of a virtual device on mac, using xcode?
> 
> Yap @Techno-Disaster :) that is it.

can you please specify this in the issue body. Because most of the setup/ run part using flutter run is done already in the current readme, so people might get confused on what they have to do.

**Comment by gaurivn** [comment]
@isabelcosta , can instructions to run iOS apps with Flutter on iOS devices (since iOS emulators require Mac) from Linux machine be included? Please check [here](https://stackoverflow.com/questions/40567540/is-it-possible-to-develop-ios-apps-with-flutter-on-a-linux-virtual-machine). I haven't run so far. Had a doubt cause Flutter does not come with iOS on Windows android studio but it has an iOS folder on Linux android studio. Wanted to know if it works on Linux. I'll try later today or tomorrow and text here if it works for me.

**Comment by techno-disaster** [comment]
@gaurivn you cannont have a ios emulator on a linux machine, there might be some hacks around it, not that i know off but apple just dosen't allow this. Also I'm not sure what you have found in the stackoverflow link, but the iOS folder is created when you do ```flutter create <appname>``` .

**Comment by gaurivn** [comment]
@Techno-Disaster , okay I get what you said. I'm sorry, my mistake I thought I could run the iOS app on an iOS device from Linux.

**Comment by techno-disaster** [comment]
@isabelcosta this looks sane as #62 which already has a PR #78 up. closing this for now. Feel free to open it if there is some issue. 
Thank You
