### ISSUE TITLE
Single option mentorship availabiliy at Sign Up

### ISSUE THREAD

**Issue by isabelcosta** [bartekpacia/mentorship-client#59]
## Description

As a user just signing up,
I need a clear definition of the roles I can have in the app,
so that I can start benefiting from the app.

Android app already has this option, so you can follow it.

## Screenshots of the issue

Android version:

![android version of this issue](https://user-images.githubusercontent.com/11148726/81499262-3c3a8400-92c2-11ea-9aad-ca087ddad551.png)

Flutter version:

![flutter out dated version](https://user-images.githubusercontent.com/11148726/81499276-5a07e900-92c2-11ea-86f2-a160caac1970.png)

### Update [Required]
- [ ] Make the mentorship availability at sign up single option

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
🤷‍♀️

**Comment by techno-disaster** [comment]
@isabelcosta are you sure this option is available on the android client sign up page? I just checked and mine dosen't have it. To be clear i'm running the latest build from apk branch of mentorship-android

**Comment by techno-disaster** [comment]
Any ways this looks like a useful feature. @anitab-org/mentorship-flutter-maintainers  can I work on this? :)

**Comment by isabelcosta** [comment]
@Techno-Disaster the PR is still being made in a PR. So its soon to be done. I will assign this to you, since the other issue you were assigned is done

**Comment by techno-disaster** [comment]
cools. I will start working on this asap

**Comment by bartekpacia** [comment]
@isabelcosta I don't quite understand this
`
As a user just signing up,
I need a clear definition of the roles I can have in the app,
so that I can start benefiting from the app.
`

IMHO checkboxes are clearer and a go-to solution when there's a multi-choice to be made. Radio buttons would be applicable if user could be only a mentor or only a mentee.

**Comment by techno-disaster** [comment]
> @isabelcosta I don't quite understand this
> `As a user just signing up, I need a clear definition of the roles I can have in the app, so that I can start benefiting from the app.`
> 
> IMHO checkboxes are clearer and a go-to solution when there's a multi-choice to be made. Radio buttons would be applicable if user could be only a mentor or only a mentee.

@bartekpacia  yes, but sometimes the user just doesn't know if there is a option where he can select both the options. Like maybe he/she thinks i can only register for mentor OR mentee?

**Comment by bartekpacia** [comment]
But that's what check boxes are for...If they want to select second option, they'll click it, and it will work (checkbox will be checked). Using radio buttons for this use case is a design anti-pattern.

**Comment by techno-disaster** [comment]
> But that's what check boxes are for...If they want to select second option, they'll click it, and it will work (checkbox will be checked). Using radio buttons for this use case is a design anti-pattern.

its also possible that the user thinks only 1 option is selectable? so showing them the both option is just playing safe. what do you think about this?

**Comment by bartekpacia** [comment]
I get you, but almost always, if the user wants to click something, they'll just click and see what happens.
BTW Here are the [Material Design specs](https://material.io/components/selection-controls) that explain this well

**Comment by isabelcosta** [comment]
@bartekpacia I appreaciate your concern. I thought that single option would make it clearer that one can be a mentor and a mentee. Having checkboxes does not seem to me to make it clear.

I already asked this in  Community Open Session and I remember that at least @annabauza contributed to this discussion and we understood it as the best option.

Having 3 options for single selection: Mentee, mentor and Mentee & Mentor (Both), seems a bit more clear then making it 2 options: Mentee, Mentor for multiple selections since its just 2 options.

I will bring this up to Zulip, so we have more opinions [here](https://anitab-org.zulipchat.com/#narrow/stream/216323-design/topic/Mentorship.20System.20-.20Redesign/near/198483597)

**Comment by isabelcosta** [comment]
@bartekpacia as of now the vote was for having the single option with mentor, mentee, and both. This can be revisited later, it's not that its set in stone. We need designers to get more involved in this project, but until we get to that stage, we can go with the majority of votes. What do you think? https://anitab-org.zulipchat.com/#narrow/stream/216323-design/topic/Mentorship.20System.20-.20Redesign/near/198483597 
cc @Techno-Disaster

**Comment by techno-disaster** [comment]
> @bartekpacia as of now the vote was for having the single option with mentor, mentee, and both. This can be revisited later, it's not that its set in stone. We need designers to get more involved in this project, but until we get to that stage, we can go with the majority of votes. What do you think? https://anitab-org.zulipchat.com/#narrow/stream/216323-design/topic/Mentorship.20System.20-.20Redesign/near/198483597
> cc @Techno-Disaster

I honestly think both are fine. But as #82 is already up we should go with that. We can ofcourse change it later, it's basically 5-6 lines of code ig.
