### ISSUE TITLE
Change link to commit message guideline on CONTRIBUTING.md

### ISSUE THREAD

**Issue by isabelcosta** [bartekpacia/mentorship-client#61]
## Description
As a contributor,
I need to know the commit message style guide,
so that I can contribute according to guidelines.

The current link on CONTRIBUTING.md redirects to mentorship-android

### Update [Required]
- [ ] Replace the current Commit Message Style Guide link for this link: https://github.com/anitab-org/mentorship-flutter/wiki/Commit-Message-Style-Guide

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
30 min

**Comment by vj-codes** [comment]
Heyy I would like to work on this

**Comment by techno-disaster** [comment]
@vj-codes  Considering you are a first time I'll remove this from #97 and assign it to you. Feel free to ping here if you are stuck while working on this
