### ISSUE TITLE
Separate Installations Readme 

### ISSUE THREAD

**Issue by sakshivij** [bartekpacia/mentorship-client#62]
**Is your feature request related to a problem? Please describe.**
Current Readme file contains everything about the project with it's setup. There are various steps that are missing and can be improved.

**Describe the solution you'd like**
I would like to propose a separate markdown file that would contain details about the project setup along with GIF's to increase readability. One more benefit would be that the md file can further be enhanced any time in future.

**Comment by isabelcosta** [comment]
@sakshivij I am happy to assign this to you, I just have one doubt. What is the scope of the installation documentation? Which environment do you wish to focus on?

**Comment by sakshivij** [comment]
@isabelcosta Both. Apart from that I would also like to add GIF which explain how to install various dependencies, that makes the process whole lot easier to understand.

One example is the flutter and dart plugin.. that needs to be installed first time

**Comment by isabelcosta** [comment]
That would be awesome @sakshivij :) thank you for proposing this 🤗 I love when people give this much attention to documentation!

**Comment by techno-disaster** [comment]
Hey @sakshivij , can you update us about where you are with this PR?

**Comment by sakshivij** [comment]
It's work in progress. I'm submitting an initial PR for review within few hours.
