### ISSUE TITLE
Don't track generated files

### ISSUE THREAD

**Issue by bartekpacia** [bartekpacia/mentorship-client#63]
**Describe the problem**
Some of the code in this project(boilerplate to communicate with the API) is generated using [chopper](https://pub.dev/packages/chopper) package. This isn't a good practice, because generated code shouldn't be included under VCS like Git (for those who have experience with JS, it's like including `node_modules`).

Photo example:
<img width="307" alt="Screenshot 2020-05-12 at 11 53 23 PM" src="https://user-images.githubusercontent.com/40357511/81749415-e1fd1700-94ab-11ea-923e-2150ab0749b3.png">

**Expected behavior**
Generated files, i.e those with `chopper` in their names, should be excluded (= added to the `.gitignore`) and removed from Git.

**Comment by techno-disaster** [comment]
looks like a good first timer task :)

**Comment by bartekpacia** [comment]
You're right @Techno-Disaster, I didn't think about this.

**Comment by techno-disaster** [comment]
Moved to #97

**Comment by HaripriyaB** [comment]
Closed via #103

**Comment by techno-disaster** [comment]
Umm #103 doesn't fix this?

**Comment by HaripriyaB** [comment]
> 
> 
> Umm #103 doesn't fix this?

#103 Description says it fixes Don't track generated files issue..... doesn't it??

**Comment by techno-disaster** [comment]
Yes, i just saw it but i did not add it. Checking the edit history looks like @isabelcosta added it by mistake. Also #63 is not mentioned in the Fixes section. But I think we can close this as we had a small discussion at at the end of #103 to go ahead with this or not. Can you confirm @isabelcosta @bartekpacia
