### ISSUE TITLE
Add an alert box with a cancel / confirm button to when user wants to logout.

### ISSUE THREAD

**Issue by HaripriyaB** [bartekpacia/mentorship-client#65]
## Description
As a user, I need an alert box when I click on logout to confirm/cancel logout activity. The current state is that when I click logout it directly takes me to login page without any confirmation.

## Screenshots of the issue
![Record-2020-05-13-23-29-26-92746](https://user-images.githubusercontent.com/34762451/81856251-2b1d9b80-957e-11ea-87af-22e04ecc4083.gif)

## Acceptance Criteria
- [x] Create an alert box containing confirm and cancel button when clicked on logout button.
### Enhancement to Update 
- [x] Make the confirm button to take me to login page and cancel button to abort logout activity.

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

**Comment by isabelcosta** [comment]
@HaripriyaB your issue description is amazing with that GIF 👏👏👏

**Comment by HaripriyaB** [comment]
Can I pick up this issue as a coding team member? Can anyone assign me for this issue?

**Comment by bartekpacia** [comment]
@HaripriyaB okay, go on!
