### ISSUE TITLE
Add loading indicators

### ISSUE THREAD

**Issue by techno-disaster** [bartekpacia/mentorship-client#67]
## Description
As a user I would like to see the status of various tasks, like changing password, saving profile,etc
I would like to see a loading indicator when the process is running, instead of just a snack bar once the process has finished.
The following are the tasks where i would like to see it:
1. Change password
2. Saving profile.
3. (will add more incase I find any, feel free to add other such processes in the comments below)

### Update [Required]
- [ ] Add loading indicators

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

**Comment by techno-disaster** [comment]
I hope some first timer picks this up, if not I'll ask the other maintainers to assign it to me :) good luck

**Comment by techno-disaster** [comment]
completed all PRs apart from first timers, also looks like no one wants to pick this up. so.. @anitab-org/mentorship-flutter-maintainers  can I work on this? :smile:

**Comment by bartekpacia** [comment]
go ahead @Techno-Disaster

**Comment by techno-disaster** [comment]
3 day update : almost finished working on this locally kinda stuck due to a git issue
