### ISSUE TITLE
Add confirm password field and see password feature to change password popUp.

### ISSUE THREAD

**Issue by techno-disaster** [bartekpacia/mentorship-client#76]
## Description
As a user I would like to see what password I'm typing and would like to confirm it, so that i don't have to change password again incase of a typo while changing the password.

### Update [Required]
- [ ] Added confirm password feature
- [ ] Added see password feature
 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by techno-disaster** [comment]
will waiit for first timers to pick this up

**Comment by bharat-1809** [comment]
Can I work on this issue?

**Comment by techno-disaster** [comment]
@bharat-1809  sure, will assign it to you.
