### ISSUE TITLE
Create Github Action

### ISSUE THREAD

**Issue by techno-disaster** [bartekpacia/mentorship-client#8]
**Is your feature request related to a problem? Please describe.**
Adding this github action will make sure that none of the PRs include any changes which will break the app.

**Describe the solution you'd like**
Build a Github Action which will trigger a workflow to build an app on IOS and Android everytime we recieve a Pull Request

**Describe alternatives you've considered**
I have considered Travis CI but imho github action was the easiest to implement and has good integration with github itself

**Additional context**

**Comment by isabelcosta** [comment]
The feature request part could have some text ;) @Techno-Disaster

**Comment by techno-disaster** [comment]
ah sorry, i have updated the issue @isabelcosta

**Comment by isabelcosta** [comment]
@Techno-Disaster is perfect now :) 👏
