### ISSUE TITLE
Make disabled textfields grey on profile page

### ISSUE THREAD

**Issue by techno-disaster** [bartekpacia/mentorship-client#84]
**Is your feature request related to a problem? Please describe.**
Currently there is no difference in the profile page when editing is on or off. 

**Describe the solution you'd like**
I would like the profile page to be greyed out (suggesting that it is disabled), if i haven't selected editing mode to be on. 

**Additional context**

| Android version (how it should be) | Flutter Version (how it is) |
|-------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------|
| ![Screenshot_20200522-100401123](https://user-images.githubusercontent.com/52817235/82631676-b0a2ea80-9c13-11ea-8b99-19f2e00ea429.jpg) | ![Screenshot_20200522-100416214](https://user-images.githubusercontent.com/52817235/82631681-b4cf0800-9c13-11ea-85a7-a4356f650c1a.jpg) |

**Comment by techno-disaster** [comment]
Couldn't really think of a way doing this 🤔, but a hack would be adding opacity to the page and as the editing button is a FAB it won't be affected, same with the navbar and appbar. (wont be affected)
Result : 
![Screenshot_20200522-101735807](https://user-images.githubusercontent.com/52817235/82632376-a8e44580-9c15-11ea-8642-ccc8eb0b1172.jpg)

Incase anyone knows a better way to achieve this please reply. Thank You

**Comment by techno-disaster** [comment]
Just to be clear, this issue is still unassigned and anyone can ask us to get assigned. I'm just doing this because i wanted to try it out for myself.

**Comment by bharat-1809** [comment]
Can I work on this?

**Comment by techno-disaster** [comment]
@bharat-1809 sure.

**Comment by bharat-1809** [comment]
@Techno-Disaster even I couldn't find a more subtle way of doing this. So should I move forward with the opacity approach?

**Comment by techno-disaster** [comment]
@bharat-1809 yes, i guess you can, because if we take a look at the android profile page the whole page is greyed out too.

**Comment by bharat-1809** [comment]
> @bharat-1809 yes, i guess you can, because if we take a look at the android profile page the whole page is greyed out too.

Okay, I'll work on it. Thanks :)
