### ISSUE TITLE
Use pagination feature on Members screen

### ISSUE THREAD

**Issue by isabelcosta** [bartekpacia/mentorship-client#85]
## Description

As a user,
I need to see the list of members in the mentorship system,
so that I can select my mentor/mentee.

The backend API specification:

![image](https://user-images.githubusercontent.com/11148726/82815291-c7a24080-9e90-11ea-90e2-af747a2c33cf.png)

Nice to know:
- The default number of users is 10, and the default page is 1
- When the list as reached the end, it will simply return an empty list.
- PR that added pagination feature to `/users` and `/users/verified` API: https://github.com/anitab-org/mentorship-backend/pull/541
## Mocks

N/A

### Update [Required]
- [ ] Use pagination when fetching users
- [ ] When scrolling, fetch more users and fill the list (while showing a loader indicator)

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
5 hours

**Comment by techno-disaster** [comment]
@anitab-org/mentorship-flutter-maintainers  can i try this?

**Comment by isabelcosta** [comment]
@Techno-Disaster have you finished other issues you were assigned?

**Comment by techno-disaster** [comment]
> @Techno-Disaster have you finished other issues you were assigned?

yes the PRs are already up iirc

**Comment by bartekpacia** [comment]
Good luck!

**Comment by techno-disaster** [comment]
### EDIT : After some googling found out that I wasn't being patient enought and they were just infos/warnings :see_no_evil: . Not deleting this comment , as someone else might have a similar question

@bartekpacia I needed to refresh the chopper files but when i ```flutter pub run build_runner build --delete-conflicting-outputs``` run  I keep getting this 
```

[INFO] Generating build script...
[INFO] Generating build script completed, took 1.2s

[WARNING] Deleted previous snapshot due to missing asset graph.
[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 44.9s

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 2.1s

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 4ms

[INFO] Running build...
[INFO] Generating SDK summary...
[SEVERE] chopper_generator:chopper_generator on lib/screens/request_detail/bloc/request_detail_state.dart:

Bad state: Unexpected diagnostics:
/home/Techno-Disaster/Flutter/flutter/bin/cache/dart-sdk/lib/internal/internal.dart:172:16 - This requires the 'non-nullable' language feature to be enabled.
[INFO] 2.0s elapsed, 1/17 actions completed.
[INFO] 3.1s elapsed, 1/17 actions completed.
[INFO] 4.2s elapsed, 1/17 actions completed.
[INFO] 5.3s elapsed, 1/17 actions completed.
[INFO] 6.4s elapsed, 1/17 actions completed.
[INFO] 7.5s elapsed, 1/17 actions completed.
[INFO] 8.6s elapsed, 1/17 actions completed.
[INFO] 9.7s elapsed, 1/17 actions completed.
[INFO] 10.8s elapsed, 1/17 actions completed.
[INFO] 11.9s elapsed, 1/17 actions completed.
[INFO] 13.0s elapsed, 1/17 actions completed.
[INFO] 14.1s elapsed, 1/17 actions completed.
[INFO] 15.2s elapsed, 1/17 actions completed.
[WARNING] No actions completed for 15.1s, waiting on:
  - chopper_generator:chopper_generator on lib/screens/request_detail/bloc/request_detail_bloc.dart
  - chopper_generator:chopper_generator on lib/screens/request_detail/bloc/request_detail_event.dart
  - chopper_generator:chopper_generator on lib/screens/request_detail/bloc/bloc.dart
  - chopper_generator:chopper_generator on lib/screens/request_detail/request_detail.dart
  - chopper_generator:chopper_generator on lib/screens/member_profile/user_data_list.dart
  .. and 11 more
```

**Comment by bartekpacia** [comment]
Might be something related to Flutter / package version. I've never encountered this 🤷‍♀️

**Comment by isabelcosta** [comment]
I think this issue resolution will solve #36
