### ISSUE TITLE
Fix Pull Request Template

### ISSUE THREAD

**Issue by techno-disaster** [bartekpacia/mentorship-client#9]
**Describe the bug**
I tried renaming the file but still could not get the pull request template to work as it does in the other repos. This is the [pull_request_template.md](https://github.com/anitab-org/mentorship-flutter/blob/develop/.github/PULL_REQUEST_TEMPLATE/pull_request_template.md)

**To Reproduce**
1. Go to '[Pull Requests](https://github.com/anitab-org/mentorship-flutter/pulls)'
2. Click on 'New Pull Request'
3. Select base and head or fork 
4. See error 'Pull request template isn't loaded in the PR box'

**Expected behavior**
Pull request template is pre-loaded when contributor clicks new pull request

**Comment by bartekpacia** [comment]
[This might be useful](https://stackoverflow.com/questions/52139192/github-pull-requests-template-not-showing/52139815)

**Comment by techno-disaster** [comment]
@bartekpacia would you like to work on this?
