### ISSUE TITLE
Add Loading indicator when a task is created and marked as complete

### ISSUE THREAD

**Issue by HaripriyaB** [bartekpacia/mentorship-client#94]
**Is your feature request related to a problem? Please describe.**
Yes.  

1. When a user creates a task, after clicking create button, there is a delay of 1-2 seconds for a response from the app which is not user-freindly. 
2. Similar situation when a user marks a task as completed it stands still for 2sec.

**Describe the solution you'd like**
When a user creates a task, it has to show a loading indicator.
Similarly when a user checks the task item as completed it has to show a loading indicator.

**Additional context**
Current version of Task created: 
![Record-2020-06-11-17-49-47-92746](https://user-images.githubusercontent.com/34762451/84386494-12e97c80-ac0f-11ea-8452-b7db172d685e.gif)
Current version of Task marked as complete:
![Record-2020-06-11-17-51-03-92746](https://user-images.githubusercontent.com/34762451/84386800-960ad280-ac0f-11ea-9e4a-29ee89b9269a.gif)

**Comment by techno-disaster** [comment]
A similar issue had been already submitted (#67) and the PR for it is already up (#83) . Will merge changes for this PR in that.
