### ISSUE TITLE
Make separate sections for tasks to do and tasks completed 

### ISSUE THREAD

**Issue by HaripriyaB** [bartekpacia/mentorship-client#95]
**Is your feature request related to a problem? Please describe.**
The tasks section is not organized to show completed tasks and yet to complete tasks.

**Describe the solution you'd like**
There should be two sections/drop sections to show to-do tasks and completed tasks separately. Just like in Android version of Mentorship.

**Additional context**
Android version: 
![](https://user-images.githubusercontent.com/34762451/84390446-3adbde80-ac15-11ea-8fe0-add86b5d5eae.png)

Flutter version:
![](https://user-images.githubusercontent.com/34762451/84390449-3dd6cf00-ac15-11ea-82d9-38400c1a1598.png)

**Comment by techno-disaster** [comment]
Moved to #97

**Comment by techno-disaster** [comment]
> Moved to #97

Removed from #97 because this is kind off a big issue. If anyone from @anitab-org/coding-team is free to take it up please do :)

**Comment by HaripriyaB** [comment]
I'll take up?

**Comment by techno-disaster** [comment]
> I'll take up?

sure, assigning to you. all the best :)

**Comment by HaripriyaB** [comment]
I think I don't have bandwidth for this atm. So making it available.

**Comment by gaurivn** [comment]
I would like to work on this issue.

**Comment by HaripriyaB** [comment]
sure @gaurivn Assigning it to you.

**Comment by techno-disaster** [comment]
@gaurivn any updates on the issue?

**Comment by gaurivn** [comment]
I did try working on it, but I don't have the bandwidth for it now, so unassigning myself.

**Comment by techno-disaster** [comment]
@anitab-org/coding-team Does anyone want to take this up?

**Comment by nandini45** [comment]
@Techno-Disaster  can i work on it? but beforehand can you explain me what is this about. ,meaning i understand the issue but what the people who worked on it said that bandwidth is not there.

**Comment by bharat-1809** [comment]
Can I work on this?

**Comment by techno-disaster** [comment]
> Can I work on this?

sure assigned to u

**Comment by techno-disaster** [comment]
Hey @bharat-1809 any updates?

**Comment by bharat-1809** [comment]
@Techno-Disaster I am on to it. It's in progress.

**Comment by bharat-1809** [comment]
@Techno-Disaster Can I use a package for the job?

**Comment by techno-disaster** [comment]
@bharat-1809 yep sure :) just out of curiosity which one are you using?

**Comment by bharat-1809** [comment]
@Techno-Disaster I am using the Expandable package v4

**Comment by techno-disaster** [comment]
ah ok sure :)
