### ISSUE TITLE
Add mark as done comfirmation dialog when clicked on checkbox of a task

### ISSUE THREAD

**Issue by HaripriyaB** [bartekpacia/mentorship-client#96]
**Is your feature request related to a problem? Please describe.**
When  user clicks on the checkbox of task, it directly marks as done without confirming the user.

**Describe the solution you'd like**
Show a dialog box when a task is checked by the user. Like the one in android version.

**Additional context**
Android version:
![Record-2020-06-11-18-08-40-184af](https://user-images.githubusercontent.com/34762451/84391196-44b21180-ac16-11ea-9050-bbde19d9421b.gif)

Flutter version:
![Record-2020-06-11-17-51-03-92746](https://user-images.githubusercontent.com/34762451/84391278-63b0a380-ac16-11ea-84d8-4f504c5b6510.gif)

**Comment by techno-disaster** [comment]
Moved to #97

**Comment by Anirudhk07** [comment]
Can I take this up ?

**Comment by HaripriyaB** [comment]
@Anirudhk07 There is an existing PR for this issue [here](https://github.com/anitab-org/mentorship-flutter/pull/103) so I recommend you to see for any other issue.
