### ISSUE TITLE
Maintainance.

### ISSUE THREAD

**Issue by techno-disaster** [bartekpacia/mentorship-client#97]
### Issue
We have some issues piling up, so as per May's instructions, this issue consists of several first timer and other simpler issues combined. These are the issues you need to work on: 
#60 #63 #64 #96
Each of the above issue  already has a well defined body which tells what the issue is about, refer that when you are working on that issue.

### Definition of Done
- [x] #60 
- [ ] #63 
- [x] #64 
- [x]  #96

**Comment by techno-disaster** [comment]
@anitab-org/mentorship-flutter-maintainers Can I work on this?

**Comment by techno-disaster** [comment]
@anitab-org/mentorship-flutter-maintainers  @anitab-org/mentorship-managers  I got no confirmation if I can work on this or not? please confirm, Thank You

**Comment by Akanksha1212** [comment]
Hi @Techno-Disaster, If you don't have any other issues assigned at the moment, then go ahead.

**Comment by techno-disaster** [comment]
imo #95 isn't really a first timer/small issue so removing from this issue, because this issue was mainly meant to clear small issues piling up due to lack of first timer contributors
